---
- hosts: all
  gather_facts: yes
  become: yes
  vars:
    user_name: "ansible-runner"
    uid: "30020"
    gid: "30020"
    gh_account: "znz"

  tasks:
  - name: "ansible-runner group"
    ansible.builtin.group:
      name: "{{ user_name }}"
      state: present
      gid: "{{ gid }}"
  - name: "ansible-runner user"
    ansible.builtin.user:
      name: "{{ user_name }}"
      comment: "Ansible Runner"
      uid: "{{ uid }}"
      group: "{{ user_name }}"
      shell: "/bin/sh"

  - name: "Allow sudo"
    copy:
      content: |
        {{ user_name }} ALL=(ALL) NOPASSWD:ALL
      dest: "/etc/sudoers.d/local-ansible"
      validate: "/usr/sbin/visudo -csf %s"
      mode: "0440"

  - name: "Update authorized_keys from gh"
    ansible.posix.authorized_key:
      user: "{{ user_name }}"
      state: present
      key: "https://github.com/{{ gh_account }}.keys"
      comment: "github.com/{{ gh_account }}"
      key_options: "restrict"
    when: "lookup('env', 'UPDATE_SSH_KEYS')"

  - name: "Add AllowUsers to sshd_config"
    lineinfile:
      dest: "/etc/ssh/sshd_config"
      line: "AllowUsers {{ user_name }}"
    notify: "Restart sshd"

  - name: "Add AllowUsers SUDO_USER to sshd_config"
    lineinfile:
      dest: "/etc/ssh/sshd_config"
      line: "AllowUsers {{ ansible_env.SUDO_USER }}"
    when: "'SUDO_USER' in ansible_env"
    notify: "Restart sshd"

  handlers:
  - name: "Restart sshd"
    ansible.builtin.service:
      name: "ssh"
      state: reloaded
