---
- hosts: all
  gather_facts: no
  tasks:
  - name: 'Set debconf of apt-listchanges'
    ansible.builtin.debconf:
      name: apt-listchanges
      question: "{{ item.question }}"
      value: "{{ item.value }}"
      vtype: "{{ item.vtype }}"
    loop:
    - question: apt-listchanges/frontend
      value: "pager" # default: "pager"
      vtype: select
    - question: apt-listchanges/which
      value: "both" # default: "news"
      vtype: select
    - question: apt-listchanges/no-network
      value: "false" # default: "false"
      vtype: boolean
    - question: apt-listchanges/email-address
      value: "root" # default: "root"
      vtype: string
    - question: apt-listchanges/email-format
      value: "text" # default: "text"
      vtype: select
    - question: apt-listchanges/confirm
      value: "true" # default: "false"
      vtype: boolean
    - question: apt-listchanges/headers
      value: "true" # default: "false"
      vtype: boolean
    - question: apt-listchanges/reverse
      value: "true" # default: "false"
      vtype: boolean
    - question: apt-listchanges/save-seen
      value: "true" # default: "true"
      vtype: boolean

  - name: 'Gather the package facts'
    ansible.builtin.package_facts:
      manager: auto

  - name: 'dpkg-reconfigure apt-listchanges'
    command: 'dpkg-reconfigure -f noninteractive apt-listchanges'
    when: '"apt-listchanges" in ansible_facts.packages'
