---
- hosts: mdns
  gather_facts: no
  become: yes

  tasks:
  - name: "Enable global mdns"
    lineinfile:
      dest: "/etc/systemd/resolved.conf"
      regexp: "^#?MulticastDNS="
      line: "MulticastDNS=yes"
    notify: "Restart systemd-resolved.service"

  - name: "Create drop-in directory"
    ansible.builtin.file:
      path: "/etc/systemd/network/10-netplan-{{ item }}.network.d"
      state: directory
      owner: "root"
      group: "root"
      mode: "0755"
    loop: "{{ mdns_interfaces }}"

  - name: "Add mdns.conf"
    ansible.builtin.copy:
      content: |
        [Network]
        MulticastDNS=yes
      dest: "/etc/systemd/network/10-netplan-{{ item }}.network.d/mdns.conf"
      mode: "0444"
      owner: "root"
      group: "root"
    loop: "{{ mdns_interfaces }}"
    notify: "Reload systemd-networkd.service"

  handlers:
  - name: "Restart systemd-resolved.service"
    ansible.builtin.service:
      name: "systemd-resolved.service"
      state: restarted
  - name: "Reload systemd-networkd.service"
    ansible.builtin.service:
      name: "systemd-networkd.service"
      state: reloaded
