---
- hosts: all
  gather_facts: no
  tasks:
  - name: 'Gather the package facts'
    ansible.builtin.package_facts:
      manager: auto
  - name: 'Create /etc/needrestart/conf.d/50local.conf'
    copy:
      content: |
        $nrconf{restart} = 'a';
      dest: '/etc/needrestart/conf.d/50local.conf'
      mode: '0444'
      owner: 'root'
      group: 'root'
    when: '"needrestart" in ansible_facts.packages'
