- hosts: ramlog
  become: yes
  gather_facts: no
  vars:
    ansible_ssh_pipelining: yes
  tasks:
  # systemd-analyze cat-config systemd/journald.conf
  - name: "Create drop-in directory for journald.conf"
    ansible.builtin.file:
      path: "/etc/systemd/journald.conf.d"
      state: directory
      owner: "root"
      group: "root"
      mode: "0755"

  # journalctl --disk-usage
  # sudo rm -r /var/log/journal
  - name: "Set Storage=volatile"
    ansible.builtin.copy:
      content: |
        [Journal]
        Storage=volatile
      dest: "/etc/systemd/journald.conf.d/storage.conf"
      mode: "0444"
      owner: "root"
      group: "root"
    notify: "Restart systemd-journald.service"

  - name: "Set ForwardToSyslog=no"
    ansible.builtin.copy:
      content: |
        [Journal]
        ForwardToSyslog=no
      dest: "/etc/systemd/journald.conf.d/syslog.conf"
      mode: "0444"
      owner: "root"
      group: "root"
    notify: "Restart systemd-journald.service"

  - name: "Remove rsyslog"
    ansible.builtin.apt:
      name: rsyslog
      state: absent

  - name: "Mount tmpfs on /tmp"
    ansible.posix.mount:
      src: tmpfs
      path: /tmp
      fstype: tmpfs
      opts: "defaults,noatime,size=128m"
      state: mounted

  - name: "Remove snapd"
    ansible.builtin.apt:
      name: snapd
      state: absent

  # systemd-analyze cat-config systemd/timesyncd.conf --tldr
  - name: "Create drop-in directory for timesyncd.conf"
    ansible.builtin.file:
      path: "/etc/systemd/timesyncd.conf.d"
      state: directory
      owner: "root"
      group: "root"
      mode: "0755"

  - name: "Set SaveIntervalSec=infinity"
    ansible.builtin.copy:
      content: |
        [Time]
        SaveIntervalSec=infinity
      dest: "/etc/systemd/timesyncd.conf.d/SaveIntervalSec.conf"
      mode: "0444"
      owner: "root"
      group: "root"
    notify: "Restart systemd-timesyncd.service"

  # - name: "Remove /var/lib/systemd/timesync/clock"
  #   ansible.builtin.file:
  #     path: "/var/lib/systemd/timesync/clock"
  #     state: absent

  handlers:
  - name: "Restart systemd-journald.service"
    ansible.builtin.service:
      name: "systemd-journald.service"
      state: restarted

  - name: "Restart systemd-timesyncd.service"
    ansible.builtin.service:
      name: "systemd-timesyncd.service"
      state: restarted
