---
- hosts: raspi
  become: yes
  gather_facts: no
  vars:
    ansible_ssh_pipelining: yes
    lan_subnet: "192.168.253.0/24"
    gateway_router: "192.168.253.1"
  tasks:
  - name: "Ignore SSDP"
    community.general.ufw:
      rule: deny
      from: "{{ lan_subnet }}"
      from_port: "1900"
      proto: "udp"
      direction: "in"
      comment: "Ignore SSDP"

  - name: "Allow ECHONET-Lite"
    community.general.ufw:
      rule: allow
      from_port: "3610"
      to: "ff02::1"
      port: "3610"
      proto: "udp"
      direction: "in"
      comment: "ECHONET-Lite"

  - name: "Allow out NAT-PMP"
    community.general.ufw:
      rule: allow
      to: "{{ gateway_router }}"
      port: "5351"
      proto: "udp"
      direction: "out"
      comment: "NAT-PMP"

  - name: "Allow out SSDP"
    community.general.ufw:
      rule: allow
      to: "{{ gateway_router }}"
      port: "1900"
      proto: "udp"
      direction: "out"
      comment: "SSDP"

  - name: "Allow out TCP to the gateway router"
    community.general.ufw:
      rule: allow
      to: "{{ gateway_router }}"
      port: "30000:50000" # random port?
      proto: "tcp"
      direction: "out"
      comment: "TCP to gateway"

  - name: "Ignore UDP from nasne, chromecast"
    community.general.ufw:
      rule: deny
      from: "{{ lan_subnet }}"
      from_port: "32000:61000" # random port?
      port: "32000:61000" # random port?
      proto: "udp"
      direction: "in"
      comment: "Ignore UDP"

  - name: "Enable global mdns"
    ansible.builtin.lineinfile:
      dest: "/etc/ufw/after6.rules"
      line: "{{ item }}"
      insertbefore: "^# don't log noisy services by default$"
    loop:
      - "-A ufw6-after-input -p icmpv6 --icmpv6-type 131 -d ff02::1:ff00:0 -j ACCEPT"
      - "-A ufw6-after-input -p icmpv6 --icmpv6-type 135 -m hl --hl-eq 254 -j ACCEPT"
