---
- hosts: remote-dev-env
  become: yes
  gather_facts: no
  vars:
    ansible_ssh_pipelining: yes # Fix "Failed to set permissions on the temporary files Ansible needs to create when becoming an unprivileged user"
  tasks:
  - name: 'sshd: StreamLocalBindUnlink yes'
    ansible.builtin.copy:
      content: |
        StreamLocalBindUnlink yes
      dest: '/etc/ssh/sshd_config.d/StreamLocalBindUnlink.conf'
      mode: '0444'
      owner: 'root'
      group: 'root'
    notify: 'Restart sshd'

  - name: 'Install docker.io'
    ansible.builtin.apt:
      name: 'docker.io'

  - name: 'adduser ubuntu docker'
    ansible.builtin.user:
      name: 'ubuntu'
      append: yes
      groups: 'docker'

  - name: 'Install pass'
    ansible.builtin.apt:
      name: 'pass'

  handlers:
    - name: 'Restart sshd'
      systemd:
        name: 'ssh.service'
        state: restarted
        enabled: yes
