---
- hosts: ufw
  become: yes
  roles:
  - znz.ufw
- hosts: conoha_u01_lxd_instance
  become: yes
  tasks:
  - name: 'Allow out to apt-cacher-ng'
    community.general.ufw:
      rule: allow
      port: '3142'
      proto: 'tcp'
      direction: 'out'
      comment: 'apt-cacher-ng'
- hosts: lima
  become: yes
  tasks:
  - name: 'Allow out to host address'
    community.general.ufw:
      rule: allow
      direction: 'out'
      from_ip: '192.168.5.15'
      interface: 'eth0'
      proto: 'udp'
      to_ip: '192.168.5.2'
      comment: 'Allow out to host address'
