---
- hosts: ufw
  become: yes
  roles:
  - znz.ufw
- hosts: lima
  become: yes
  tasks:
  - name: 'Gather the package facts'
    ansible.builtin.package_facts:
      manager: auto
  - name: 'Allow out to host address'
    community.general.ufw:
      rule: allow
      direction: 'out'
      from_ip: '192.168.5.15'
      interface: 'eth0'
      proto: 'udp'
      to_ip: '192.168.5.2'
      comment: 'Allow out to host address'
    when: '"ufw" in ansible_facts.packages'
