- hosts: conoha-u01
  become: yes
  vars:
  tasks:
  - name: 'Copy hosts'
    copy:
      src: 'tmp/wireguard/wg2022/hosts'
      dest: '/etc/coredns/wg2022/hosts'
      owner: 'root'
      group: 'root'
      mode: '0444'
  roles:
  - coredns
