---
- hosts: zabbix_server
  gather_facts: no
  vars:
    ansible_ssh_pipelining: yes
  tasks:
  - name: 'Install python3-pip'
    ansible.builtin.apt:
      name: python3-pip
  - name: 'pip zabbix-api'
    ansible.builtin.pip:
      name: zabbix-api

  - name: 'Create host groups'
    community.zabbix.zabbix_group:
      host_groups:
      - 'macOS hosts'
      - 'Other'
      # 既存のホストグループ:
      #- 'Linux servers'
      #- 'Virtual machines'
      #- 'Zabbix servers'
      state: present
      login_user: '{{ zabbix_login_user }}'
      login_password: '{{ zabbix_login_password }}'
      server_url: '{{ zabbix_server_url }}'

  - name: 'Allow out to zabbix-agent'
    community.general.ufw:
      rule: allow
      port: '10050'
      proto: 'tcp'
      direction: 'out'
      comment: 'zabbix-agent'

  # $ grep listen /etc/nginx/conf.d/zabbix.conf
  #        listen          [::]:8080;
  - name: 'Allow to zabbix-frontend'
    community.general.ufw:
      rule: allow
      port: '8080'
      proto: 'tcp'
      comment: 'zabbix-frontend'

  - name: 'Create Linux hosts'
    community.zabbix.zabbix_host:
      host_name: '{{ item.name }}'
      host_groups:
      - 'Linux servers'
      link_templates:
      - 'Linux by Zabbix agent'
      interfaces:
      - type: agent
        main: 1
        useip: 1
        ip: '{{ item.ip }}'
        port: '10050'
      tls_accept: 2
      tls_connect: 2
      tls_psk: '{{ lookup("file", "tmp/zabbix-agent/" + item.name + ".psk") }}'
      tls_psk_identity: 'PSK {{ item.name }}'

      state: '{{ item.state | default("present") }}'
      status: '{{ item.status | default("enabled") }}'
      login_user: '{{ zabbix_login_user }}'
      login_password: '{{ zabbix_login_password }}'
      server_url: '{{ zabbix_server_url }}'
    loop:
    - name: 'conoha-d02'
      ip: 'fdcb:a987:6543:2022::c0:d2'
    - name: 'conoha-u01'
      ip: 'fdcb:a987:6543:2022::c0:1'
    - name: 'lima-default'
      ip: 'fdcb:a987:6543:2022::11:1'
    - name: 'saving-stinkbug'
      ip: 'fdcb:a987:6543:2022::c001:55'

  - name: 'Create macOS hosts'
    community.zabbix.zabbix_host:
      host_name: '{{ item.name }}'
      visible_name: '{{ item.visible_name | default("") }}'
      description: '{{ item.description | default("") }}'
      host_groups:
      - 'macOS hosts'
      link_templates:
      - 'macOS'
      interfaces:
      - type: agent
        main: 1
        useip: 1
        ip: '{{ item.ip }}'
        port: '10050'
      tls_accept: 2
      tls_connect: 2
      tls_psk: '{{ lookup("file", "tmp/zabbix-agent/" + item.name + ".psk") }}'
      tls_psk_identity: '{{ item.psk_identity }}'

      state: '{{ item.state | default("present") }}'
      status: '{{ item.status | default("enabled") }}'
      login_user: '{{ zabbix_login_user }}'
      login_password: '{{ zabbix_login_password }}'
      server_url: '{{ zabbix_server_url }}'
    loop:
    - name: 'knmbp21'
      ip: 'fdcb:a987:6543:2022::30:21'
      psk_identity: 'knmbp21'
      # Mounted filesystem discovery のフィルタに
      # {#FSNAME} 一致しない ^/Volumes/com\.apple\.TimeMachine\.localsnapshots/
      # を設定した。
