---
- name: "Install wireguard"
  ansible.builtin.apt:
    name: wireguard
    state: latest
  become: yes
  tags: wireguard_apt
- import_tasks: "genkey.yml"
  tags: wireguard_genkey
- import_tasks: "conf.yml"
  tags: wireguard_conf
- import_tasks: "etc_hosts.yml"
  tags: wireguard_etc_hosts
- name: "TCP wrappers: Add lines to /etc/hosts.allow"
  lineinfile:
    dest: "/etc/hosts.allow"
    line: "{{ item }}"
  loop: "{{ wireguard_hosts_allow }}"
  tags: wireguard_hosts_allow
