---
- name: "Install wireguard"
  ansible.builtin.apt:
    name: wireguard
    state: latest
  become: yes
  tags: wireguard_apt
- import_tasks: "genkey.yml"
  tags: wireguard_genkey
- import_tasks: "ufw.yml"
  tags: wireguard_ufw
- import_tasks: "conf.yml"
  tags: wireguard_conf
